FROM golang:1.8
ARG drone_git_ref=547514348d1836db33edeef82d68dd92620f39b4
WORKDIR /go/src/github.com/drone/drone/
RUN \
  git clone https://github.com/drone/drone.git . && \
  git checkout $drone_git_ref && \
  go get -u github.com/drone/drone-ui/dist && \
  go get -u golang.org/x/tools/cmd/cover && \
  go get -u golang.org/x/net/context && \
  go get -u golang.org/x/net/context/ctxhttp && \
  go get -u github.com/golang/protobuf/proto && \
  go get -u github.com/golang/protobuf/protoc-gen-go && \
  go build -ldflags '-extldflags "-static" -X github.com/drone/drone/version.VersionDev=1and1' -o release/drone-server github.com/drone/drone/cmd/drone-server && \
  GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags '-X github.com/drone/drone/version.VersionDev=1and1' -o release/drone-agent github.com/drone/drone/cmd/drone-agent
